/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Mon Dec 16 13:40:02 2024.
 */

#include <string.h>

#include "sim_db.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int sim_pps_sensors_pack(
    uint8_t *dst_p,
    const struct sim_pps_sensors_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->pps, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pps, 8u, 0x1fu);
    dst_p[1] |= pack_left_shift_u16(src_p->pps_inv, 5u, 0xe0u);
    dst_p[2] |= pack_right_shift_u16(src_p->pps_inv, 3u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->pps_inv, 11u, 0x03u);

    return (4);
}

int sim_pps_sensors_unpack(
    struct sim_pps_sensors_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->pps = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pps |= unpack_left_shift_u16(src_p[1], 8u, 0x1fu);
    dst_p->pps_inv = unpack_right_shift_u16(src_p[1], 5u, 0xe0u);
    dst_p->pps_inv |= unpack_left_shift_u16(src_p[2], 3u, 0xffu);
    dst_p->pps_inv |= unpack_left_shift_u16(src_p[3], 11u, 0x03u);

    return (0);
}

int sim_pps_sensors_init(struct sim_pps_sensors_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct sim_pps_sensors_t));

    return 0;
}

uint16_t sim_pps_sensors_pps_encode(float value)
{
    return (uint16_t)(value);
}

float sim_pps_sensors_pps_decode(uint16_t value)
{
    return ((float)value);
}

bool sim_pps_sensors_pps_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t sim_pps_sensors_pps_inv_encode(float value)
{
    return (uint16_t)(value);
}

float sim_pps_sensors_pps_inv_decode(uint16_t value)
{
    return ((float)value);
}

bool sim_pps_sensors_pps_inv_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int sim_cooling_sensors_pack(
    uint8_t *dst_p,
    const struct sim_cooling_sensors_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->thermocouple, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->thermocouple, 8u, 0x1fu);

    return (2);
}

int sim_cooling_sensors_unpack(
    struct sim_cooling_sensors_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->thermocouple = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->thermocouple |= unpack_left_shift_u16(src_p[1], 8u, 0x1fu);

    return (0);
}

int sim_cooling_sensors_init(struct sim_cooling_sensors_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct sim_cooling_sensors_t));

    return 0;
}

uint16_t sim_cooling_sensors_thermocouple_encode(float value)
{
    return (uint16_t)(value);
}

float sim_cooling_sensors_thermocouple_decode(uint16_t value)
{
    return ((float)value);
}

bool sim_cooling_sensors_thermocouple_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int sim_inverter_temp_pack(
    uint8_t *dst_p,
    const struct sim_inverter_temp_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->temp, 8u, 0x07u);

    return (2);
}

int sim_inverter_temp_unpack(
    struct sim_inverter_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->temp = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);

    return (0);
}

int sim_inverter_temp_init(struct sim_inverter_temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct sim_inverter_temp_t));

    return 0;
}

uint16_t sim_inverter_temp_temp_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float sim_inverter_temp_temp_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool sim_inverter_temp_temp_is_in_range(uint16_t value)
{
    return (value <= 1200u);
}

int sim_fan_ctrl_pack(
    uint8_t *dst_p,
    const struct sim_fan_ctrl_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->fan_pwm_duty, 0u, 0x7fu);

    return (1);
}

int sim_fan_ctrl_unpack(
    struct sim_fan_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->fan_pwm_duty = unpack_right_shift_u8(src_p[0], 0u, 0x7fu);

    return (0);
}

int sim_fan_ctrl_init(struct sim_fan_ctrl_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct sim_fan_ctrl_t));

    return 0;
}

uint8_t sim_fan_ctrl_fan_pwm_duty_encode(float value)
{
    return (uint8_t)(value);
}

float sim_fan_ctrl_fan_pwm_duty_decode(uint8_t value)
{
    return ((float)value);
}

bool sim_fan_ctrl_fan_pwm_duty_is_in_range(uint8_t value)
{
    return (value <= 100u);
}
